package com.cpst.postal.settlement.md.model;

// Generated 2012-12-7 11:01:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BPermProvCity generated by hbm2java
 */
public class BPermProvCity implements java.io.Serializable {

	private static final long serialVersionUID = -840425144481416649L;
	// 区划代码
	private String districtCode;
	// 省名
	private String provinceName;
	// 市名
	private String cityName;
	// 县名
	private String countyName;
	// 省拼音名
	private String provinceSim;
	// 市拼音名
	private String citySim;
	// 区县拼音名
	private String countySim;
	// 维度
	private char degree;
	private Date dataDate;

	public BPermProvCity() {
	}

	/**  
	 * 取得 区划代码.
	 */
	public String getDistrictCode() {
		return this.districtCode;
	}

	/**
	 * 设置 区划代码.
	 */
	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	/**  
	 * 取得 省名.
	 */
	public String getProvinceName() {
		return this.provinceName;
	}

	/**
	 * 设置 省名.
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	/**  
	 * 取得 地区名.
	 */
	public String getCityName() {
		return this.cityName;
	}

	/**
	 * 设置 地区名.
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**  
	 * 取得 县名.
	 */
	public String getCountyName() {
		return this.countyName;
	}

	/**
	 * 设置 县名.
	 */
	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	/**  
	 * 取得 省拼音名.
	 */
	public String getProvinceSim() {
		return this.provinceSim;
	}

	/**
	 * 设置 省拼音名.
	 */
	public void setProvinceSim(String provinceSim) {
		this.provinceSim = provinceSim;
	}

	/**  
	 * 取得 地区拼音名.
	 */
	public String getCitySim() {
		return this.citySim;
	}

	/**
	 * 设置 地区拼音名.
	 */
	public void setCitySim(String citySim) {
		this.citySim = citySim;
	}

	/**  
	 * 取得 区县拼音名.
	 */
	public String getCountySim() {
		return this.countySim;
	}

	/**
	 * 设置 区县拼音名.
	 */
	public void setCountySim(String countySim) {
		this.countySim = countySim;
	}

	/**  
	 * 取得 维度.
	 */
	public char getDegree() {
		return this.degree;
	}

	/**
	 * 设置 维度.
	 */
	public void setDegree(char degree) {
		this.degree = degree;
	}

	/**  
	 */
	public Date getDataDate() {
		return this.dataDate;
	}

	/**
	 */
	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

}
