package com.cpst.postal.settlement.md.model;

// Generated 2012-12-7 10:45:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BPermExchangeOffice generated by hbm2java
 */
public class BPermExchangeOffice implements java.io.Serializable {

	private static final long serialVersionUID = 6916152167604633453L;
	// ID
	private Integer seqId;
	// 3位互换局代码
	private String BCode;
	// 互换局名拼音
	private String BEname;
	// 互换局中文名
	private String BCname;
	// 省名代码
	private String BProvcode;
	// 省名
	private String BProvname;
	// 所属地区市名
	private String BCityname;
	// 所属地区市代码
	private String BCitycode;
	// 更新日期
	private Date dataDate;

	public BPermExchangeOffice() {
	}

	public BPermExchangeOffice(Integer seqId, String BCode) {
		super();
		this.seqId = seqId;
		this.BCode = BCode;
	}

	/**  
	 * 取得 ID.
	 */
	public Integer getSeqId() {
		return this.seqId;
	}

	/**
	 * 设置 ID.
	 */
	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	/**  
	 * 取得 3位互换局代码.
	 */
	public String getBCode() {
		return this.BCode;
	}

	/**
	 * 设置 3位互换局代码.
	 */
	public void setBCode(String BCode) {
		this.BCode = BCode;
	}

	/**  
	 * 取得 互换局名拼音.
	 */
	public String getBEname() {
		return this.BEname;
	}

	/**
	 * 设置 互换局名拼音.
	 */
	public void setBEname(String BEname) {
		this.BEname = BEname;
	}

	/**  
	 * 取得 互换局中文名.
	 */
	public String getBCname() {
		return this.BCname;
	}

	/**
	 * 设置 互换局中文名.
	 */
	public void setBCname(String BCname) {
		this.BCname = BCname;
	}

	/**  
	 * 取得 省名代码.
	 */
	public String getBProvcode() {
		return this.BProvcode;
	}

	/**
	 * 设置 省名代码.
	 */
	public void setBProvcode(String BProvcode) {
		this.BProvcode = BProvcode;
	}

	/**  
	 * 取得 省名.
	 */
	public String getBProvname() {
		return this.BProvname;
	}

	/**
	 * 设置 省名.
	 */
	public void setBProvname(String BProvname) {
		this.BProvname = BProvname;
	}

	/**  
	 * 取得 所属地区市名.
	 */
	public String getBCityname() {
		return this.BCityname;
	}

	/**
	 * 设置 所属地区市名.
	 */
	public void setBCityname(String BCityname) {
		this.BCityname = BCityname;
	}

	/**  
	 * 取得 所属地区市代码.
	 */
	public String getBCitycode() {
		return this.BCitycode;
	}

	/**
	 * 设置 所属地区市代码.
	 */
	public void setBCitycode(String BCitycode) {
		this.BCitycode = BCitycode;
	}

	/**  
	 * 取得 更新日期.
	 */
	public Date getDataDate() {
		return this.dataDate;
	}

	/**
	 * 设置 更新日期.
	 */
	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

}
