package com.cpst.postal.settlement.md.model;

/**
 * BPermRolesLevel generated by hbm2java
 */
public class BPermRolesLevel implements java.io.Serializable {


	// 序号
	private Integer seqId;
	// 角色ID
	private Integer roleId;
	// 员工级别
	private Integer positionsLevel;
	// 角色类型 （0 是管理员，1 是非管理员）
	private Integer roleTypeId;
	// 子系统ID
	private String subSys;

	public BPermRolesLevel() {
	}

	public BPermRolesLevel(Integer seqId) {
		this.seqId = seqId;
	}

	public BPermRolesLevel(Integer seqId, Integer roleId,
			Integer positionsLevel, Integer roleTypeId, String subSys) {
		this.seqId = seqId;
		this.roleId = roleId;
		this.positionsLevel = positionsLevel;
		this.roleTypeId = roleTypeId;
		this.subSys = subSys;
	}

	/**  
	 * 取得 序号.
	 */
	public Integer getSeqId() {
		return this.seqId;
	}

	/**
	 * 设置 序号.
	 */
	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	/**  
	 * 取得 角色ID.
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * 设置 角色ID.
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**  
	 * 取得 员工级别.
	 */
	public Integer getPositionsLevel() {
		return this.positionsLevel;
	}

	/**
	 * 设置 员工级别.
	 */
	public void setPositionsLevel(Integer positionsLevel) {
		this.positionsLevel = positionsLevel;
	}

	/**  
	 * 取得 角色类型 （0 是管理员，1 是非管理员）.
	 */
	public Integer getRoleTypeId() {
		return this.roleTypeId;
	}

	/**
	 * 设置 角色类型 （0 是管理员，1 是非管理员）.
	 */
	public void setRoleTypeId(Integer roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	/**  
	 * 取得 子系统ID.
	 */
	public String getSubSys() {
		return this.subSys;
	}

	/**
	 * 设置 子系统ID.
	 */
	public void setSubSys(String subSys) {
		this.subSys = subSys;
	}

}

