package com.cpst.postal.settlement.md.model;

import java.util.Set;

// Generated 2012-12-6 15:33:40 by Hibernate Tools 3.4.0.CR1

/**
 * BPermRoles generated by hbm2java
 */
public class BRole implements java.io.Serializable {

	private static final long serialVersionUID = 8098092805375541806L;
	private Integer seqId;
	private String name;
	private Integer orders;
	private String memo;
	
	private Set<BResourcePermission> resourcePermissions;
	
	
	public Set<BResourcePermission> getResourcePermissions() {
		return resourcePermissions;
	}

	public void setResourcePermissions(Set<BResourcePermission> resourcePermissions) {
		this.resourcePermissions = resourcePermissions;
	}

	public BRole() {
	}

	/**  
	 */
	public Integer getSeqId() {
		return this.seqId;
	}

	/**
	 */
	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	/**  
	 */
	public String getName() {
		return this.name;
	}

	/**
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**  
	 */
	public Integer getOrders() {
		return this.orders;
	}

	/**
	 */
	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	/**  
	 */
	public String getMemo() {
		return this.memo;
	}

	/**
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

}
