package com.cpst.postal.settlement.user.model;

// Generated 2012-11-28 14:38:24 by Hibernate Tools 3.4.0.CR1

/**
 * BAccountDataAcl generated by hbm2java
 */
public class BAccountDataAcl implements java.io.Serializable {

	private static final long serialVersionUID = -4733215037037885674L;
	private Integer id;
	private Integer positionsLevel;
	private String belongTo;
	private Integer positionsRefId;
	private Integer dataPermission;
	private Integer userId;
	
	public BAccountDataAcl() {
	}

	public BAccountDataAcl(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPositionsLevel() {
		return positionsLevel;
	}

	public void setPositionsLevel(Integer positionsLevel) {
		this.positionsLevel = positionsLevel;
	}

	public String getBelongTo() {
		return belongTo;
	}

	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

	public Integer getPositionsRefId() {
		return positionsRefId;
	}

	public void setPositionsRefId(Integer positionsRefId) {
		this.positionsRefId = positionsRefId;
	}

	public Integer getDataPermission() {
		return dataPermission;
	}

	public void setDataPermission(Integer dataPermission) {
		this.dataPermission = dataPermission;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}



}
