package com.cpst.postal.settlement.user.model;

// Generated 2012-12-25 19:37:44 by Hibernate Tools 3.4.0.CR1

/**
 * BPermUserRole generated by hbm2java
 */
public class BPermUserRole implements java.io.Serializable {

	private static final long serialVersionUID = 6561610700277944441L;
	private Integer userId;
	private Integer roleId;
	private Integer seqId;

	public BPermUserRole() {
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getSeqId() {
		return seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

}
