package com.cpst.postal.settlement.user.model;

import java.util.Date;
import java.util.Set;

// Generated 2012-12-6 15:33:40 by Hibernate Tools 3.4.0.CR1

/**
 * BPermUsers generated by hbm2java
 */
public class BUser implements java.io.Serializable {

	private static final long serialVersionUID = -6005232084209889838L;
	private Integer seqId;
	private Integer version;
	private String loginName;
	private String password;
	private String realName;
	private String tel;
	private String EMail;
	private Integer emsOrCommon;
	private Integer dataEntryStaffFlag;
	private Integer positionsLevel;
	private String code;
	private String description;
	private String delFlag;
	private Date createDate;
	
	
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	private Set<BRole> roles;

	public BUser() {
	}

	public Set<BRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<BRole> roles) {
		this.roles = roles;
	}

	/**  
	 */
	public Integer getSeqId() {
		return this.seqId;
	}

	/**
	 */
	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	/**  
	 */
	public Integer getVersion() {
		return this.version;
	}

	/**
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**  
	 */
	public String getLoginName() {
		return this.loginName;
	}

	/**
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**  
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**  
	 */
	public String getRealName() {
		return this.realName;
	}

	/**
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**  
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**  
	 */
	public String getEMail() {
		return this.EMail;
	}

	/**
	 */
	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	/**  
	 */
	public Integer getEmsOrCommon() {
		return this.emsOrCommon;
	}

	/**
	 */
	public void setEmsOrCommon(Integer emsOrCommon) {
		this.emsOrCommon = emsOrCommon;
	}

	/**  
	 */
	public Integer getDataEntryStaffFlag() {
		return this.dataEntryStaffFlag;
	}

	/**
	 */
	public void setDataEntryStaffFlag(Integer dataEntryStaffFlag) {
		this.dataEntryStaffFlag = dataEntryStaffFlag;
	}

	/**  
	 */
	public Integer getPositionsLevel() {
		return this.positionsLevel;
	}

	/**
	 */
	public void setPositionsLevel(Integer positionsLevel) {
		this.positionsLevel = positionsLevel;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	/**  
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
